### ISSUE TITLE
Forth

### ISSUE THREAD

**Issue by larsbrinkhoff** [Z80-mini/Z80_mini-Software#1]
I'm curious about you Z80 Forth!

**Comment by bernd-ulmann** [comment]
Hello Mr. Brinkhoff - 
what would you like to know about the Forth interpreter? It is a
straight-forward port of Brad Rodriguez' Camel Forth
(http://www.bradrodriguez.com/papers/moving1.htm).
 Regard - Bernd Ulmann.

Prof. Dr. Bernd Ulmann
Schwalbacher Strasse 31
65307 Bad Schwalbach
Germany

**Comment by larsbrinkhoff** [comment]
Thank you.  Will you post it to this repository?

**Comment by bernd-ulmann** [comment]
No as it is Brad's brain child - please contact him, I can't decide for him.
The source code is available on his homepage.

**Comment by larsbrinkhoff** [comment]
Ok, thanks!
